Remove Windows 7 and align with other
gazebosim/gz-plugin pull request #122
Opened 2023-09-02 22:21 UTC by Bi0T1N

# 🦟 Bug fix

## Summary
- remove Windows 7
- align description style with other README files

related to https://github.com/gazebosim/gazebo_test_cases/issues/133

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-09-03 21:02 UTC, ahcorde approved these changes

2023-09-04 07:55 UTC, ahcorde requested changes

2023-09-04 07:55 UTC, ahcorde commented on README.md
> +Windows     | [![Build Status](https://build.osrfoundation.org/job/ignition_plugin-ci-main-windows7-amd64/badge/icon)](https://build.osrfoundation.org/job/ignition_plugin-ci-main-windows7-amd64/)
```suggestion
Windows     | [![Build Status](https://build.osrfoundation.org/view/ign-garden/job/ign_plugin-gz-2-win/badge/icon)](https://build.osrfoundation.org/view/ign-garden/job/ign_plugin-gz-2-win/)
```

2023-09-07 15:36 UTC, mjcarroll approved these changes

2023-09-11 16:39 UTC, merged