ign -> gz Macro Migration : gz-plugin
gazebosim/gz-plugin pull request #87
Opened 2022-06-06 21:45 UTC by methylDragon

See: https://github.com/gazebo-tooling/release-tools/issues/737

2022-06-07 02:01 UTC, chapulina requested changes

2022-06-07 02:39 UTC, methylDragon commented on register/include/ignition/plugin/Register.hh
> +  GZ_ADD_PLUGIN(PluginClass, ...)
https://github.com/gazebosim/gz-plugin/pull/87/commits/868fceb5b88767f5e2dbc3dbecad0bd5148d8578

2022-06-07 17:26 UTC, chapulina approved these changes
LGTM with 🟢 CI

2022-06-09 04:04 UTC, chapulina approved these changes

2022-06-17 22:41 UTC, methylDragon commented
@osrf-jenkins run tests please!

2022-06-17 22:47 UTC, merged